scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8100']
        labels:
          application: 'Recipes Service Application'
    basic_auth:
      username: user
      password: userpass